import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import products from '../products.json'
import { initiateCheckout } from '../lib/payments';

export default function Home() {
  console.log("products", products);
  return (
    <div className={styles.container}>
      <Head>
        <title>Store with stripe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my store!!
        </h1>

        <div className={styles.grid}>

          {products.map(product =>{
            const {title, description, image, price, id} = product;
            return (
              <div className={styles.card} key={id}>
                <Image src={image} alt={title} width="100%" height="100%" />
                <h2>{title}</h2>
                <p>{description}</p>
                <p>${price}</p>
                <button className={styles.button} onClick={() => initiateCheckout({
                  lineItems: [
                    {
                      price: id,
                      quantity: 1
                    }
                  ]
                })}>Buy now</button>
              </div>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
