import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import products from '../products.json'
import { initiateCheckout } from '../lib/payments';

let defaultProduct = {
  products: {}
}

export default function Home() {
  const [cart, updateCart] = useState(defaultProduct);

  const cartItems = Object.keys(cart.products).map(key => {
    const product = products.find(({ id }) => `${id}` === `${key}`);
    return {
      ...cart.products[key],
      pricePerItem: product.price
    }
  })

  const subTotal = cartItems.reduce((acc, {pricePerItem, quantity}) => {
    return acc + (pricePerItem * quantity)
  }, 0)

  const totalItems = cartItems.reduce((acc, { quantity}) => {
    return acc + quantity
  }, 0)
  console.log("subtotal:", subTotal)

  function addToCart({ id } = {}){
    updateCart(prev => {
      let cartState = {...prev}

      if(cartState.products[id]){
        cartState.products[id].quantity = cartState.products[id].quantity + 1
      }else{
        cartState.products[id] = {
          id, 
          quantity: 1
        }
      }
      return cartState
    })
  }
  function checkOut(){
    initiateCheckout({
      lineItems: cartItems.map(item => {
        return {
          price: item.id,
          quantity: item.quantity
        }
      })
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Store with stripe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my store!!
        </h1>

        <p>
          <strong>Items:</strong> {totalItems}
          <br/>
          <strong>Total Cost:</strong> ${subTotal}
          <br/>
          <button className={styles.button} onClick={() => checkOut()}>Check Out</button>
        </p>

        <div className={styles.grid}>

          {products.map(product =>{
            const {title, description, image, price, id} = product;
            return (
              <div className={styles.card} key={id}>
                <Image src={image} alt={title} width="100%" height="100%" />
                <h2>{title}</h2>
                <p>{description}</p>
                <p>${price}</p>
                <button className={styles.button} onClick={() => {
                  addToCart({id})
                }
              }>Add to cart</button>
            </div>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
